In [1]:
import pandas as pd
pd.set_option('display.max_colwidth', None)

### Exploratory Data Analysis.

In [2]:
df = pd.read_csv('DataSetTwitter.csv', encoding='ISO-8859-1')

df.head()

,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer. You shoulda got David Carr of Third Day to do it. ;D"
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by texting it... and might cry as a result School today also. Blah!
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Managed to save 50% The rest go out of bounds
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all. i'm mad. why am i here? because I can't see you all over there."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew

> _Let's put names in which columns to the dataframe above_

In [3]:
df.columns = ['sentiment', 'user_id', 'date', 'flag', 'user', 'text']

df.head()

,sentiment,user_id,date,flag,user,text
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by texting it... and might cry as a result School today also. Blah!
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Managed to save 50% The rest go out of bounds
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all. i'm mad. why am i here? because I can't see you all over there."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew

In [4]:
# Let us look at the size of the data:
df.shape

(1599999, 6)

> _Let's get the number of elements in our dataset_

In [5]:
df.size

9599994

> _Lets look at data type_

In [6]:
df.dtypes

sentiment     int64
user_id       int64
date         object
flag         object
user         object
text         object
dtype: object

> _Let's see if the dataset is missing any values._

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599999 entries, 0 to 1599998
Data columns (total 6 columns):
 #   Column     Non-Null Count    Dtype
---  ------     --------------    -----
 0   sentiment  1599999 non-null  int64
 1   user_id    1599999 non-null  int64
 2   date       1599999 non-null  object
 3   flag       1599999 non-null  object
 4   user       1599999 non-null  object
 5   text       1599999 non-null  object
dtypes: int64(2), object(4)
memory usage: 73.2+ MB

> _There are no missing values. I just need the columns 'sentiment' and 'text' for sentiment analysis._

In [8]:
df = df[['sentiment', 'text']]

df.head()

,sentiment,text
0,0,is upset that he can't update his Facebook by texting it... and might cry as a result School today also. Blah!
1,0,@Kenichan I dived many times for the ball. Managed to save 50% The rest go out of bounds
2,0,my whole body feels itchy and like its on fire
3,0,"@nationwideclass no, it's not behaving at all. i'm mad. why am i here? because I can't see you all over there."
4,0,@Kwesidei not the whole crew

> _Let’s check how many instances there are for each class_

In [9]:
df.groupby('sentiment').describe()

             text
            count  unique                        top freq
sentiment
0          799999  790184  isPlayer Has Died! Sorry   210
4          800000  793506              good morning   118

> _As we can see, the number of unique samples is diferent of samples for each class, therefore the dataset has duplicates rows. Let's delete the duplicate rows._

In [10]:
df = df.drop_duplicates()
df.groupby('sentiment').describe()

             text          \
            count  unique
sentiment
0          790184  790184
4          793506  793506

                                                                                                                            \
                                                                                                                       top
sentiment
0          is upset that he can't update his Facebook by texting it... and might cry as a result  School today also. Blah!
4                                                                             I LOVE @Health4UandPets u guys r the best!!


          freq
sentiment
0            1
4            1

In [11]:
#lets just make a quick modification instead of 4 to positive, lets change to 1 - positive
df['sentiment'] = df['sentiment'].map({0: 0, 4: 1})

In [12]:
df.groupby('sentiment').describe()

             text          \
            count  unique
sentiment
0          790184  790184
1          793506  793506

                                                                                                                            \
                                                                                                                       top
sentiment
0          is upset that he can't update his Facebook by texting it... and might cry as a result  School today also. Blah!
1                                                                             I LOVE @Health4UandPets u guys r the best!!


          freq
sentiment
0            1
1            1

> _As we can see above, we have some special characters that we need to remove, like #, @, and url. Let's clean our data_

> Let's check each one

In [13]:
print(df[df['text'].str.contains('@')])

         sentiment  \
1                0
3                0
4                0
6                0
7                0
...            ...
1599988          1
1599990          1
1599992          1
1599993          1
1599998          1

                                                                                                                                          text
1                                                    @Kenichan I dived many times for the ball. Managed to save 50%  The rest go out of bounds
3                              @nationwideclass no, it's not behaving at all. i'm mad. why am i here? because I can't see you all over there.
4                                                                                                                @Kwesidei not the whole crew
6                                          @LOLTrish hey  long time no see! Yes.. Rains a bit ,only a bit  LOL , I'm fine thanks , how's you ?
7                                                                                                         @Tatiana_K nope they didn't have it
...                                                                                                                                        ...
1599988                                                                                                     @Ms_Hip_Hop im glad ur doing well
1599990  @rmedina @LaTati Mmmm  That sounds absolutely perfect... but my schedule is full. I won't have time to lay in bed until Sunday. Ugh!!
1599992                                                                                                                      @SCOOBY_GRITBOYS
1599993   @Cliff_Forster Yeah, that does work better than just waiting for it  In the end I just wonder if I have time to keep up a good blog.
1599998                                                                         happy #charitytuesday @theNSPCC @SparksCharity @SpeakingUpH4H

[744596 rows x 2 columns]

In [14]:
print(df[df['text'].str.contains('#')])

         sentiment  \
82               0
174              0
189              0
192              0
330              0
...            ...
1599936          1
1599951          1
1599984          1
1599987          1
1599998          1

                                                                                                                                                text
82                                                                                                                       @markhardy1974 Me too  #itm
174                                                                 @machineplay I'm so sorry you're having to go through this. Again.  #therapyfail
189         I activated my Selfcontrol block early, meaning I can't check out the new QC.  Regularizing my internal clock is might be difficult. #fb
192                         @goodlaura What about Reese dying on #TTSC? And season finale next week.  #24 boring, Madame President is a crazy woman.
330                                                                                                My man crush Jake Peavy let me down  #gayforpeavy
...                                                                                                                                              ...
1599936   @siahoney I am good thanks!    How is #Eric, I haven't heard anything in awhile, have u visited him recently?  I hope he is feeling better
1599951                                          #Traveltuesday @GuyNGirlTravels Because their tweets are hilarious LOL and they're great travelers
1599984  if ur the lead singer in a band, beware falling prey to LSD &quot;Lead Singer Disease&quot; http://tinyurl.com/n65xjt  #music #haveyouever?
1599987                @Roy_Everitt ha- good job. that's right - we gotta throw that #bigrun tag EVERYWHERE! I wanna get it trending before I start
1599998                                                                               happy #charitytuesday @theNSPCC @SparksCharity @SpeakingUpH4H

[36493 rows x 2 columns]

In [15]:
print(df[df['text'].str.contains('www')])

         sentiment  \
42               0
49               0
133              0
180              0
221              0
...            ...
1599549          1
1599567          1
1599609          1
1599713          1
1599920          1

                                                                                                                                                   text
42                                                @JonathanRKnight Awww I soo wish I was there to see you finally comfortable! Im sad that I missed it
49                    Broadband plan 'a massive broken promise' http://tinyurl.com/dcuc33 via www.diigo.com/~tautao Still waiting for broadband we are
133           I'm missing you babe..  but as long as your alive I'm happy.. Yawwwnn.. I'm tired my love imma try to sleep hopefully you had a headstart
180                                                                                             Check out my mug  http://www.erika-obscura.blogspot.com
221                   @PaulaAbdul awww, Good luck Paula!! Please don't work too hard  but I hope you have fun  Your new album is gonna be amazing!  xxx
...                                                                                                                                                 ...
1599549                                                   @Jesse just started using www.socialtoo.com - great twool!  Thx for recommending @guykawasaki
1599567                                     @NicciLuvsMollie no problem ;) and awww  I'm sure you'll get lots of amazing pics of her (and them) too lol
1599609                                                                                         Keep listening - thanks  www.reverbnation.com/keithhide
1599713                      Portraits ordered. More http://www.twitpic.com/73gng HOPE cards ordered. CDs burned. Emails sent. I'm hopping on my bike.
1599920  I just switched back to Opera (using the moi skin). It's really fast &amp; stable to work with - I'm loving it  http://www.opera.com/download/

[19812 rows x 2 columns]

In [16]:
print(df[df['text'].str.contains('http')])

         sentiment  \
36               0
49               0
73               0
94               0
99               0
...            ...
1599960          1
1599972          1
1599980          1
1599984          1
1599995          1

                                                                                                                                                text
36                                                                                     @MissXu sorry! bed time came here (GMT+1)   http://is.gd/fNge
49                 Broadband plan 'a massive broken promise' http://tinyurl.com/dcuc33 via www.diigo.com/~tautao Still waiting for broadband we are
73                                                                                       Why won't you show my location?!   http://twitpic.com/2y2es
94                                                             Strider is a sick little puppy  http://apps.facebook.com/dogbook/profile/view/5248435
99              Body Of Missing Northern Calif. Girl Found: Police have found the remains of a missing Northern California girl .. http://tr.im/imji
...                                                                                                                                              ...
1599960                                                @crgrs359 Skip the aquarium and check out these fish   A lot cheaper lol http://bit.ly/2lQbBv
1599972                                                                           http://twitpic.com/7jp4n - OMG! Office Space... I wanna steal it.
1599980                                                                            Another Commenting Contest! [;: Yay!!!  http://tinyurl.com/m6j2an
1599984  if ur the lead singer in a band, beware falling prey to LSD &quot;Lead Singer Disease&quot; http://tinyurl.com/n65xjt  #music #haveyouever?
1599995                                                               TheWDB.com - Very cool to hear old Walt interviews!  â« http://blip.fm/~8bmta

[68888 rows x 2 columns]

> _Let's use Regular Expressions to remove these special characters and clean our data. We're gonna use a Python module named 're'._

In [17]:
# Let's create a function to do all the processes at once
import re

def preprocess_clean_text(text):
   text = re.sub(r'\d+', '', text).lower() #remove numbers and put the text in lower case
   text = re.sub(r'https\S+|http\S+|www\S+', '', text) #removing urls like https://, http://, www.
   text = re.sub(r'@\w+', '', text) # removing @
   text = re.sub(r"#(\w+)", r'\1', text) #removing #
   return text

In [18]:
df['clean_text'] = df['text'].apply(preprocess_clean_text)

In [19]:
df.head()

,sentiment,text,clean_text
0,0,is upset that he can't update his Facebook by texting it... and might cry as a result School today also. Blah!,is upset that he can't update his facebook by texting it... and might cry as a result school today also. blah!
1,0,@Kenichan I dived many times for the ball. Managed to save 50% The rest go out of bounds,i dived many times for the ball. managed to save % the rest go out of bounds
2,0,my whole body feels itchy and like its on fire,my whole body feels itchy and like its on fire
3,0,"@nationwideclass no, it's not behaving at all. i'm mad. why am i here? because I can't see you all over there.","no, it's not behaving at all. i'm mad. why am i here? because i can't see you all over there."
4,0,@Kwesidei not the whole crew,not the whole crew

In [20]:
# lets remove white spaces
def remove_rwSpace(text):
    text = text.strip()
    return text

df['clean_text'] = df['clean_text'].apply(remove_rwSpace)

> _Let's check if the cleaning process worked._

In [21]:
df.loc[6,['clean_text', 'text']]

clean_text              hey  long time no see! yes.. rains a bit ,only a bit  lol , i'm fine thanks , how's you ?
text          @LOLTrish hey  long time no see! Yes.. Rains a bit ,only a bit  LOL , I'm fine thanks , how's you ?
Name: 6, dtype: object

In [22]:
df.loc[1599998,['clean_text', 'text']]

clean_text                                              happy charitytuesday
text          happy #charitytuesday @theNSPCC @SparksCharity @SpeakingUpH4H
Name: 1599998, dtype: object

In [23]:
df.loc[1599549,['clean_text', 'text']]

clean_text                                         just started using  - great twool!  thx for recommending
text          @Jesse just started using www.socialtoo.com - great twool!  Thx for recommending @guykawasaki
Name: 1599549, dtype: object

In [24]:
df.loc[94,['clean_text', 'text']]

clean_text                                                           strider is a sick little puppy
text          Strider is a sick little puppy  http://apps.facebook.com/dogbook/profile/view/5248435
Name: 94, dtype: object

In [25]:
df.loc[368,['clean_text', 'text']]

clean_text                                                             but all says not in stock
text          @nchokkan https://www.mycomicshop.com/search?TID=395031 But all says not in stock
Name: 368, dtype: object

> _Let's work with the clean dataset now._

In [26]:
df_clean = df[['clean_text', 'sentiment']]

In [27]:
df_clean.head(10)

,clean_text,sentiment
0,is upset that he can't update his facebook by texting it... and might cry as a result school today also. blah!,0
1,i dived many times for the ball. managed to save % the rest go out of bounds,0
2,my whole body feels itchy and like its on fire,0
3,"no, it's not behaving at all. i'm mad. why am i here? because i can't see you all over there.",0
4,not the whole crew,0
5,need a hug,0
6,"hey long time no see! yes.. rains a bit ,only a bit lol , i'm fine thanks , how's you ?",0
7,nope they didn't have it,0
8,que me muera ?,0
9,spring break in plain city... it's snowing,0